name: flujo 1
on: [push]
jobs:
  saludar:
    runs-on: ubuntu-latest 
    steps:
      - name: saludos
        run: echo "hola mundo desde github actions"

  eventos:
    runs-on: ubuntu-latest
    steps:
      - name: tipo de evento
        run: echo "el evento es:" ${{ github.event_name }}

  autor:
    runs-on: ubuntu-latest
    steps:
      - name:  el autor es
        run:  echo "autor:" ${{ github.actor }}

  secretos:
    runs-on: ubuntu-latest
    steps:
      - name: mis secretos
        run: echo "los secretos son:" ${{secrets.USERNAME}} ${{secrets.ROLE}}

  detectar_rama:
     runs-on: ubuntu-latest
     steps:
       - name: es la rama main
         if:  github.ref == 'refs/heads/main'
         run: echo "si es la rama main"

  variable_de_entorno:
     runs-on: ubuntu-latest
     env:
       FOO: "FOOZIMAN"
     steps:
       - name: el contenido de la variable de entorno es 
         run: echo "el valor es:$FOO"

  estrategias_de_versiones:
      runs-on: ubuntu-latest
      strategy:
        matrix: 
          node-version: [18,19,20]
      steps:
       - name: instalar node
         uses: actions/setup-node@v3
         with:
             node-version: ${{matrix.node-version}}

       - name: mostrar versiones
         run: echo "node version:" node --version
         
        
          
