 name: flujo 1
on: [push]
jobs:
  saludar:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: saludos
        run: echo "hola mundo desde github actions"

  eventos:
     runs-on: ubuntu-24.04-arm
     env: EVENT_NAME: ${{ github.event_name }}
     steps:
       - name: tipo de evento
         run: echo "el evento es: $EVENT_NAME" 
