name: flujo 1
on: [push]
jobs:
  saludar:
    runs-on: ubuntu-latest 
    steps:
      - name: saludos
        run: echo "hola mundo desde github actions"

  eventos:
    runs-on: ubuntu-latest
    steps:
      - name: tipo de evento
        run: echo "el evento es:" ${{ github.event_name }}
