name: flujo 1
on: [push]
jobs:
  saludar:
    runs-on: ubuntu-latest 
    steps:
      - name: saludos
        run: echo "hola mundo desde github actions"

  eventos:
    runs-on: ubuntu-latest
    steps:
      - name: tipo de evento
        run: echo "el evento es:" ${{ github.event_name }}

  autor:
    runs-on: ubuntu-latest
    steps:
      - name:  el autor es
        run:  echo "autor:" ${{ github.actor }}

  secretos:
    runs-on: ubuntu-latest
    steps:
      - name: mis secretos
        run: echo "los secretos son:" ${{secrets.USERNAME}} ${{secrets.ROLE}}
     
